### ISSUE TITLE
Error in spinner.Spin

### ISSUE THREAD

**Issue by gradinarot** [m1/gospin#2]
When i'm using
`spinner.Spin("{Apply|Use} this {special |||}{spintax|spin}")`
sometimes the output is "Use thisspintax" which means the white space after "this" is removed.

**Comment by m1** [comment]
What is your intended output?

**Comment by gradinarot** [comment]
"{special |||}" should be outputted only ~25% the time

**Comment by m1** [comment]
This has been fixed in `0.3.0`. Thanks for reporting.
